version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: srcd
    volumes:
      - ./db-data:/var/lib/postgresql/data
  
  rabbit:
    image: rabbitmq
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672

  srcd:
    build: .
    environment:
      CONFIG_DBUSER: postgres
      CONFIG_DBNAME: postgres
      CONFIG_GITHUB_TOKEN: 000b8966e33c0192ab20263d376b8e1cb6990b45
